package com.stingrayshield.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme
val md_theme_light_primary = Color(0xFF00629D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF535F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E3F7)
val md_theme_light_onSecondaryContainer = Color(0xFF101C2B)
val md_theme_light_tertiary = Color(0xFF6B5778)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF2DAFF)
val md_theme_light_onTertiaryContainer = Color(0xFF251431)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFF9ECAFF)
val md_theme_light_surfaceTint = Color(0xFF00629D)
val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
val md_theme_light_scrim = Color(0xFF000000)

// Dark theme
val md_theme_dark_primary = Color(0xFF9ECAFF)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF00497A)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_secondary = Color(0xFFBBC7DB)
val md_theme_dark_onSecondary = Color(0xFF253141)
val md_theme_dark_secondaryContainer = Color(0xFF3B4858)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7E3F7)
val md_theme_dark_tertiary = Color(0xFFD6BDE4)
val md_theme_dark_onTertiary = Color(0xFF3B2948)
val md_theme_dark_tertiaryContainer = Color(0xFF534060)
val md_theme_dark_onTertiaryContainer = Color(0xFFF2DAFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF00629D)
val md_theme_dark_surfaceTint = Color(0xFF9ECAFF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)

// Status colors
val statusNormal = Color(0xFF4CAF50)
val statusWarning = Color(0xFFFFC107)
val statusAlert = Color(0xFFFF9800)
val statusDanger = Color(0xFFE91E63)
val statusUnknown = Color(0xFF9E9E9E)

// Custom Stingray-themed colors for enhanced UX
// Light theme with security-focused colors
val stingray_light_primary = Color(0xFF1E3A5F)        // Deep navy blue for security
val stingray_light_onPrimary = Color(0xFFFFFFFF)
val stingray_light_primaryContainer = Color(0xFFD3E4FD)
val stingray_light_onPrimaryContainer = Color(0xFF001B3E)
val stingray_light_secondary = Color(0xFF565F71)
val stingray_light_onSecondary = Color(0xFFFFFFFF)
val stingray_light_secondaryContainer = Color(0xFFDAE2F9)
val stingray_light_onSecondaryContainer = Color(0xFF131C2B)
val stingray_light_tertiary = Color(0xFF705575)
val stingray_light_onTertiary = Color(0xFFFFFFFF)
val stingray_light_tertiaryContainer = Color(0xFFFBD7FC)
val stingray_light_onTertiaryContainer = Color(0xFF28132E)
val stingray_light_error = Color(0xFFBA1A1A)
val stingray_light_errorContainer = Color(0xFFFFDAD6)
val stingray_light_onError = Color(0xFFFFFFFF)
val stingray_light_onErrorContainer = Color(0xFF410002)
val stingray_light_background = Color(0xFFFEFBFF)
val stingray_light_onBackground = Color(0xFF1A1C1E)
val stingray_light_surface = Color(0xFFFEFBFF)
val stingray_light_onSurface = Color(0xFF1A1C1E)
val stingray_light_surfaceVariant = Color(0xFFE0E2EC)
val stingray_light_onSurfaceVariant = Color(0xFF44474E)
val stingray_light_outline = Color(0xFF74777F)
val stingray_light_inverseOnSurface = Color(0xFFF1F0F4)
val stingray_light_inverseSurface = Color(0xFF2F3033)
val stingray_light_inversePrimary = Color(0xFFA4C8FF)
val stingray_light_surfaceTint = Color(0xFF1E3A5F)
val stingray_light_outlineVariant = Color(0xFFC4C7D0)
val stingray_light_scrim = Color(0xFF000000)

// Dark theme with security-focused colors
val stingray_dark_primary = Color(0xFFA4C8FF)
val stingray_dark_onPrimary = Color(0xFF001E31)
val stingray_dark_primaryContainer = Color(0xFF004A77)
val stingray_dark_onPrimaryContainer = Color(0xFFD3E4FD)
val stingray_dark_secondary = Color(0xFFBEC6DC)
val stingray_dark_onSecondary = Color(0xFF283041)
val stingray_dark_secondaryContainer = Color(0xFF3E4759)
val stingray_dark_onSecondaryContainer = Color(0xFFDAE2F9)
val stingray_dark_tertiary = Color(0xFFDFBCDF)
val stingray_dark_onTertiary = Color(0xFF3E2844)
val stingray_dark_tertiaryContainer = Color(0xFF563E5C)
val stingray_dark_onTertiaryContainer = Color(0xFFFBD7FC)
val stingray_dark_error = Color(0xFFFFB4AB)
val stingray_dark_errorContainer = Color(0xFF93000A)
val stingray_dark_onError = Color(0xFF690005)
val stingray_dark_onErrorContainer = Color(0xFFFFDAD6)
val stingray_dark_background = Color(0xFF0F1419)      // Darker background for security feel
val stingray_dark_onBackground = Color(0xFFE1E2E8)
val stingray_dark_surface = Color(0xFF0F1419)
val stingray_dark_onSurface = Color(0xFFE1E2E8)
val stingray_dark_surfaceVariant = Color(0xFF44474E)
val stingray_dark_onSurfaceVariant = Color(0xFFC4C7D0)
val stingray_dark_outline = Color(0xFF8E9099)
val stingray_dark_inverseOnSurface = Color(0xFF0F1419)
val stingray_dark_inverseSurface = Color(0xFFE1E2E8)
val stingray_dark_inversePrimary = Color(0xFF1E3A5F)
val stingray_dark_surfaceTint = Color(0xFFA4C8FF)
val stingray_dark_outlineVariant = Color(0xFF44474E)
val stingray_dark_scrim = Color(0xFF000000)
